export const LIVE_CONTEXT_VERSION = 1;

export interface MemoryRecord {
  id: number;
  kind: string;
  title: string;
  body: string;
  created: number;
}

export interface FileRecord {
  id: number;
  path: string;
  touches: number;
}

export interface TurnRecord {
  id: number;
  turnIndex: number;
  summary: string;
}

export interface LiveContextInput {
  sessionKey: string;
  sessionId: number;
  revision: number;
  budgetTokens: number;
  memories: MemoryRecord[];
  files: FileRecord[];
  turns: TurnRecord[];
}

export const MEMORY_PROTOCOL = [
  "# Live context file",
  "",
  "Your context document is a real file that you own. The path is printed below.",
  "Read and rewrite it with your ordinary file tools. It is the central record of",
  "what you understand; the graph below is an index of it, not a replacement.",
  "",
  "Anything you write between the MANAGED markers is regenerated by the extension",
  "and your edits there are lost. Write above them.",
  "",
  "Wrap every code reference in backticks, using either a repository-relative path",
  "(`src/graph.ts`) or a symbol name (`GraphClient::connect`). Each turn the",
  "extension resolves them against the CodeGraph index and lists the resulting ids",
  "in the managed section, so you can cite stable ids instead of re-deriving them.",
  "",
  "- `hydradb_remember` stores a concept as a graph node, and attaches it to code",
  "  with the same backticked references, stored as CodeGraph ids.",
  "- `hydradb_recall` reads concepts back, newest first, filtered by substring.",
  "- `hydradb_neighbors` walks from a concept to the code it references.",
  "- `hydradb_forget` removes a node and its edges.",
  "- `hydradb_context` prints the context file path and its current contents.",
  "- `codegraph_resolve` resolves a path or symbol to its CodeGraph id directly.",
  "",
  "The value of the graph is why: a concept node records why a piece of code",
  "matters and what it relates to, which the code index alone cannot express.",
].join("\n");

export function estimateTokens(text: string): number {
  return Math.ceil(text.length / 4);
}

export function selectWithinBudget<T>(
  items: T[],
  budgetTokens: number,
  render: (item: T) => string,
): T[] {
  const selected: T[] = [];
  let spent = 0;
  for (const item of items) {
    const cost = estimateTokens(render(item));
    if (spent + cost > budgetTokens) break;
    selected.push(item);
    spent += cost;
  }
  return selected;
}

function renderMemory(memory: MemoryRecord): string {
  return `- [${memory.kind}] ${memory.title} (id=${memory.id})\n  ${memory.body}`;
}

function renderFile(file: FileRecord): string {
  return `- ${file.path} (id=${file.id}, touches=${file.touches})`;
}

function renderTurn(turn: TurnRecord): string {
  return `- turn ${turn.turnIndex}: ${turn.summary} (id=${turn.id})`;
}

export function buildLiveContextDocument(input: LiveContextInput): string {
  const lines: string[] = [];
  lines.push(
    `[[HYDRA_CLM version=${LIVE_CONTEXT_VERSION} session=${input.sessionKey} ` +
      `id=${input.sessionId} revision=${input.revision} budget=${input.budgetTokens}]]`,
  );

  lines.push("", "## Remembered");
  if (input.memories.length === 0) lines.push("- (none)");
  else for (const memory of input.memories) lines.push(renderMemory(memory));

  lines.push("", "## Touched files");
  if (input.files.length === 0) lines.push("- (none)");
  else for (const file of input.files) lines.push(renderFile(file));

  lines.push("", "## Recent turns");
  if (input.turns.length === 0) lines.push("- (none)");
  else for (const turn of input.turns) lines.push(renderTurn(turn));

  return lines.join("\n");
}

export function projectLiveContext(input: LiveContextInput): string {
  const header = estimateTokens(
    `[[HYDRA_CLM version=${LIVE_CONTEXT_VERSION} session=${input.sessionKey}]]`,
  );
  let remaining = Math.max(0, input.budgetTokens - header);

  const memories = selectWithinBudget(input.memories, Math.floor(remaining * 0.6), renderMemory);
  remaining -= memories.reduce((sum, item) => sum + estimateTokens(renderMemory(item)), 0);

  const files = selectWithinBudget(input.files, Math.floor(remaining * 0.5), renderFile);
  remaining -= files.reduce((sum, item) => sum + estimateTokens(renderFile(item)), 0);

  const turns = selectWithinBudget(input.turns, remaining, renderTurn);

  const document = buildLiveContextDocument({ ...input, memories, files, turns });
  return `${MEMORY_PROTOCOL}\n\n${document}`;
}

export const MANAGED_BEGIN = "<!-- HYDRA_CLM_MANAGED_BEGIN -->";
export const MANAGED_END = "<!-- HYDRA_CLM_MANAGED_END -->";
export const CONTEXT_FILE_NAME = "live-context.md";

export interface CodeRefRecord {
  id: number;
  codegraphId: string;
  kind: string;
  name: string;
  filePath: string;
}

const CODEGRAPH_KINDS =
  "file|function|method|class|struct|interface|constant|type_alias|variable|import";

const CODEGRAPH_ID = new RegExp(`^(?:${CODEGRAPH_KINDS}):[A-Za-z0-9_./\\\\-]+$`);

export function isCodegraphId(value: string): boolean {
  return CODEGRAPH_ID.test(value.trim());
}

export function extractReferences(text: string): string[] {
  const found: string[] = [];
  const seen = new Set<string>();
  const push = (value: string) => {
    const trimmed = value.trim();
    if (trimmed.length === 0 || seen.has(trimmed)) return;
    seen.add(trimmed);
    found.push(trimmed);
  };
  for (const match of text.matchAll(/`([^`\n]+)`/g)) push(match[1] ?? "");
  for (const match of text.matchAll(new RegExp(CODEGRAPH_ID.source.slice(1, -1), "g"))) {
    push(match[0]);
  }
  return found;
}

export function splitContextFile(text: string): { model: string; managed: string } {
  const begin = text.indexOf(MANAGED_BEGIN);
  const end = text.indexOf(MANAGED_END);
  if (begin === -1 || end === -1 || end < begin) return { model: text.trim(), managed: "" };
  const model = `${text.slice(0, begin)}${text.slice(end + MANAGED_END.length)}`.trim();
  return { model, managed: text.slice(begin, end + MANAGED_END.length) };
}

export function renderManagedZone(
  references: CodeRefRecord[],
  sessionKey: string,
  revision: number,
  budgetTokens = 1500,
): string {
  const lines = [
    MANAGED_BEGIN,
    `## Indexed code references (session ${sessionKey}, revision ${revision})`,
  ];
  if (references.length === 0) {
    lines.push("", "_None yet. Write backticked file paths or symbol names in your notes_");
    lines.push("_and they will be resolved to CodeGraph ids here._");
  } else {
    lines.push("");
    const shown = selectWithinBudget(
      references,
      budgetTokens,
      (ref) => `- \`${ref.codegraphId}\` (${ref.kind} ${ref.name}) in ${ref.filePath}`,
    );
    for (const ref of shown) {
      lines.push(`- \`${ref.codegraphId}\` ${ref.kind} ${ref.name} (${ref.filePath})`);
    }
    const hidden = references.length - shown.length;
    if (hidden > 0) {
      lines.push(
        "",
        `_${hidden} more reference(s) indexed but not listed here to stay inside the_`,
        `_${budgetTokens}-token budget. Use \`hydradb_neighbors\` on a concept node for its full set._`,
      );
    }
  }
  lines.push(MANAGED_END);
  return lines.join("\n");
}

export function composeContextFile(
  model: string,
  references: CodeRefRecord[],
  sessionKey: string,
  revision: number,
  budgetTokens = 1500,
): string {
  const head =
    model.trim().length > 0 ? model.trim() : "# Live context\n\n_(empty: write your notes here)_";
  return `${head}\n\n${renderManagedZone(references, sessionKey, revision, budgetTokens)}\n`;
}
