apiVersion: constraints.gatekeeper.sh/v1beta1
kind: NoDirectGuestConnect
metadata:
  name: no-direct-guest-connect
spec:
  enforcementAction: deny
  match:
    kinds:
    - apiGroups:
      - specs.publicdomainrelay.dev
      kinds:
      - CodeGraph
  parameters:
    globs:
    - test/**
    pattern: Deno\.connect
