// Vendors clm/core into hooks/vendor/core.js. A mod imports only files inside
// its own folder, and clm/core lives one directory up, so the shared core is
// bundled into the plugin instead of imported across the boundary. The bundle
// is one ES module with no `import()` and no node: builtin, because that is all
// a mod can load.
//
// `npm run build:mod` writes hooks/vendor/core.js and hooks/vendor/core.hash;
// `npm test` recomputes the hash and fails when the vendored copy is stale.

import { createHash } from "node:crypto";
import { readFileSync, readdirSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";

import { build } from "esbuild";

const here = dirname(fileURLToPath(import.meta.url));
const coreDir = join(here, "..", "clm", "core");
const vendorDir = join(here, "hooks", "vendor");

export function coreSources() {
  const files = [];
  const walk = (dir) => {
    for (const entry of readdirSync(dir, { withFileTypes: true }).sort((left, right) => (left.name < right.name ? -1 : 1))) {
      const path = join(dir, entry.name);
      if (entry.isDirectory()) walk(path);
      else if (entry.name.endsWith(".ts")) files.push(path);
    }
  };
  walk(coreDir);
  return files;
}

/** The digest of the core's own sources, not of the bundle esbuild made. */
export function coreHash() {
  const hash = createHash("sha256");
  for (const file of coreSources()) {
    hash.update(relative(coreDir, file));
    hash.update("\u0000");
    hash.update(readFileSync(file));
    hash.update("\u0000");
  }
  return hash.digest("hex");
}

export async function buildMod() {
  mkdirSync(vendorDir, { recursive: true });
  await build({
    entryPoints: [join(coreDir, "mod.ts")],
    outfile: join(vendorDir, "core.js"),
    bundle: true,
    format: "esm",
    platform: "neutral",
    target: "es2022",
    mainFields: ["module", "main"],
    conditions: ["import", "default"],
    allowOverwrite: true,
    banner: { js: "// GENERATED by `npm run build:mod` from clm/core. Do not edit." },
  });
  // The types beside the bundle. esbuild emits no declarations, and a
  // re-export of the core's .ts sources would not type-check under the engine's
  // own tsconfig (which does not allow .ts import paths), so the contract the
  // mod actually uses is written out here. It is small and closed: the ports
  // and ClmHost, which is what register.ts imports.
  writeFileSync(join(vendorDir, "core.d.ts"), CORE_TYPES);
  writeFileSync(join(vendorDir, "core.hash"), `${coreHash()}\n`);
}

const CORE_TYPES = `// GENERATED by \`npm run build:mod\` from clm/core. Do not edit.
// The public surface the mod imports; the runtime bundle is core.js.

export interface CommandResult {
  exitCode: number;
  stdout: string;
  stderr: string;
}

export interface RunOptions {
  cwd?: string;
  env?: Record<string, string>;
  stdin?: string;
  timeoutMs?: number;
}

export interface Runner {
  run(argv: readonly string[], options?: RunOptions): Promise<CommandResult>;
}

export interface FsAncestor {
  dir: string;
  name: string;
  content: string;
}

export interface FileStore {
  read(path: string): Promise<string>;
  write(path: string, text: string): Promise<void>;
  exists(path: string): Promise<boolean>;
  ancestors(request: { names: readonly string[]; of?: string; below?: string }): Promise<FsAncestor[]>;
}

export interface ProgressRecord {
  turn?: number;
  tool?: string;
  files?: string[];
  note?: string;
  at?: string;
}

export interface AppliedDelta {
  delta: unknown;
  applied: boolean;
  folded?: string;
}

export interface StateBridge {
  render(context: string): Promise<string>;
  apply(context: string, modelZone: string): Promise<AppliedDelta>;
  report(change: string, event: ProgressRecord): Promise<{ progress: number; recorded: boolean }>;
}

export interface Clock {
  now(): Date;
}

export interface HostOptions {
  bridge: StateBridge;
  files: FileStore;
  repoPath: string;
  docPath: string;
  context: string;
  change?: string;
  clock?: Clock;
}

export interface StartResult {
  path: string;
  document: string;
  changed: boolean;
}

export type Env = Readonly<Record<string, string | undefined>>;

export declare function contextDocPath(docDir: string, repository: string, context: string): string;

export declare function docDirFromEnv(env: Env, home: string | undefined): string;

export declare function docPathFromEnv(env: Env, home: string | undefined, repoPath: string, context: string): string;

export declare class ClmHost {
  constructor(options: HostOptions);
  readonly context: string;
  readonly change: string;
  start(): Promise<StartResult | undefined>;
  section(): Promise<string | undefined>;
  touched(tool: string, files: readonly string[], note?: string): Promise<void>;
  finish(note?: string): Promise<AppliedDelta | undefined>;
}
`;

if (import.meta.url === `file://${process.argv[1]}`) {
  await buildMod();
  process.stdout.write(`vendored clm/core ${coreHash().slice(0, 12)} into hooks/vendor/core.js\n`);
}
