package provisioningmanualkeymaterial

import data.lib.specd

violation[{"msg": msg, "details": details}] {
	file := input.review.object.spec.files[_]
	row := file.added[_]
	not comment(row.text)
	patterns := matched_patterns(row.text)
	count(patterns) > 0
	not ignored(file.path)
	not allowed(row.text)
	msg := sprintf("added line %s:%d makes ssh key material by hand: %q; a guest is reached through the relay's ProxyCommand over the websocket tunnel, and its keys are placed by the cloud-init user_data, so no authorized_keys is assembled and no keypair generated by hand", [file.path, row.line, trim_space(row.text)])
	details := {"file": file.path, "line": row.line, "patterns": patterns}
}

matched_patterns(text) = out {
	out := [pattern | pattern := key_patterns[_]; regex.match(pattern, text)]
}

key_patterns = out {
	out := input.parameters.patterns
} else = [`\bauthorized_keys\b`, `\bssh-keygen\b`]

ignored(path) {
	specd.matches_globs(ignored_paths, path)
}

ignored_paths = out {
	out := input.parameters.ignoredPaths
} else = [`**/*.md`]

allowed(text) {
	regex.match(input.parameters.allowPatterns[_], text)
}

comment(text) {
	regex.match(comment_patterns[_], text)
}

comment_patterns = out {
	out := input.parameters.commentPatterns
} else = [`^\s*#`, `^\s*//`, `^\s*\*`]
