package ingest

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	specsync "github.com/publicdomainrelay/graph-clm-kcp-spec/abc/sync"
)

func write(t *testing.T, path, contents string) {
	t.Helper()
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte(contents), 0o644); err != nil {
		t.Fatal(err)
	}
}

func TestPackageRootsFindsManifestsAndSkipsDependencies(t *testing.T) {
	tree := t.TempDir()
	write(t, filepath.Join(tree, "go.mod"), "module unseen\n")
	write(t, filepath.Join(tree, "greet", "deno.json"), "{}\n")
	write(t, filepath.Join(tree, "greet", "mod.ts"), "export const a = 1;\n")
	write(t, filepath.Join(tree, "node_modules", "dep", "package.json"), "{}\n")
	write(t, filepath.Join(tree, ".git", "config"), "[core]\n")

	roots, err := PackageRoots(tree)
	if err != nil {
		t.Fatal(err)
	}
	if strings.Join(roots, ",") != ".,greet" {
		t.Errorf("roots = %v, want the tree root and greet", roots)
	}
}

func TestPackageRootsAlwaysIncludesTheTreeRoot(t *testing.T) {
	tree := t.TempDir()
	write(t, filepath.Join(tree, "main.go"), "package main\n")
	roots, err := PackageRoots(tree)
	if err != nil {
		t.Fatal(err)
	}
	if len(roots) != 1 || roots[0] != "." {
		t.Errorf("roots = %v, want only the tree root", roots)
	}
}

func TestDenoImportMapHoldsTheMapAndTheMemberNames(t *testing.T) {
	tree := t.TempDir()
	write(t, filepath.Join(tree, "deno.json"), `{
  "workspace": ["lib/a", "lib/b"],
  "imports": {
    "@scope/local": "./lib/a/mod.ts",
    "@scope/npm": "npm:@scope/npm@^1"
  }
}
`)
	write(t, filepath.Join(tree, "lib", "a", "deno.json"), `{"name": "@scope/a", "version": "0.0.0"}`+"\n")
	write(t, filepath.Join(tree, "lib", "b", "deno.json"), `{"version": "0.0.0"}`+"\n")

	imports := DenoImportMap(tree)
	if imports["@scope/local"] != "./lib/a/mod.ts" {
		t.Errorf("the map entry = %q", imports["@scope/local"])
	}
	if imports["@scope/a"] != "./lib/a" {
		t.Errorf("the member name = %q", imports["@scope/a"])
	}
	if _, found := imports["@scope/npm"]; !found {
		t.Errorf("an npm entry was dropped: %v", imports)
	}
	if _, found := imports["@scope/b"]; found {
		t.Errorf("a member without a name got one: %v", imports)
	}
}

func TestDetectPartitionPicksPackageForADenoWorkspace(t *testing.T) {
	workspace := t.TempDir()
	write(t, filepath.Join(workspace, "deno.json"), `{"workspace": ["lib/a"]}`+"\n")
	if got := DetectPartition(workspace); got != "package" {
		t.Errorf("partition = %q, want package", got)
	}
	single := t.TempDir()
	write(t, filepath.Join(single, "deno.json"), `{"name": "@scope/one"}`+"\n")
	if got := DetectPartition(single); got != "directory" {
		t.Errorf("partition = %q, want directory", got)
	}
	goOnly := t.TempDir()
	write(t, filepath.Join(goOnly, "go.mod"), "module x\n")
	if got := DetectPartition(goOnly); got != "directory" {
		t.Errorf("partition = %q, want directory", got)
	}
}

func TestGeneratedDirectoriesFoldsOnlyAllGeneratedTrees(t *testing.T) {
	tree := t.TempDir()
	write(t, filepath.Join(tree, "lib", "lex", "mod.ts"), "export const a = 1;\n")
	write(t, filepath.Join(tree, "lib", "lex", "com", "a.ts"), "/*\n * THIS FILE WAS GENERATED BY \"@atproto/lex\". DO NOT EDIT.\n */\nexport const b = 2;\n")
	write(t, filepath.Join(tree, "lib", "lex", "com", "b.ts"), "/*\n * THIS FILE WAS GENERATED BY \"@atproto/lex\". DO NOT EDIT.\n */\nexport const c = 3;\n")
	write(t, filepath.Join(tree, "lib", "mixed", "gen.ts"), "// DO NOT EDIT\nexport const d = 4;\n")
	write(t, filepath.Join(tree, "lib", "mixed", "hand.ts"), "export const e = 5;\n")

	files := []specsync.SourceFile{
		{Path: "lib/lex/mod.ts"},
		{Path: "lib/lex/com/a.ts"},
		{Path: "lib/lex/com/b.ts"},
		{Path: "lib/mixed/gen.ts"},
		{Path: "lib/mixed/hand.ts"},
	}
	generated := GeneratedDirectories(tree, files)
	if !generated["lib/lex/com"] {
		t.Errorf("an all-generated directory was not folded: %v", generated)
	}
	if generated["lib/lex"] || generated["lib/mixed"] {
		t.Errorf("a directory with hand-written code was folded: %v", generated)
	}
	roots := withoutGenerated([]string{".", "lib/lex", "lib/lex/com"}, generated)
	if strings.Join(roots, ",") != ".,lib/lex" {
		t.Errorf("roots = %v", roots)
	}
}
