apiVersion: constraints.gatekeeper.sh/v1beta1
kind: ConformanceForbiddenFlow
metadata:
  name: conformance-forbidden-flow
spec:
  enforcementAction: deny
  match:
    kinds:
    - apiGroups:
      - specs.publicdomainrelay.dev
      kinds:
      - ArchitectureModel
